---
- name: learn all loop inside playbook
  hosts: all
  become: yes
  tasks:
   - name: Add serveral users on nodes
     ansible.builtin.user:
      name: "{{ item }}"
      state: present
     loop:
      - testuser1
      - testuser2
      - Anjana
      - Anju  
